export {};
const express = require('express');
const authController = require('../controller/authController');
const prodController = require('../controller/prodController');
const router = express.Router();
router.get('/', prodController.getAllProd);
router.get('/:id', prodController.getProd);
router.post('/', prodController.addProd);
router.patch('/:id', prodController.upLoad, prodController.updateProd);
module.exports = router;
