export {};
const express = require('express');
const authController = require('../controller/authController');
const shopController = require('../controller/shopController');
const router = express.Router();
router.get('/', shopController.getAllShop);
router.get('/:id', shopController.getShop);
router.post('/getRelatedShop', shopController.getRelatedShop);
router.patch('/:id', shopController.updateShop);
router.use(authController.protect);
router.post('/', shopController.upLoad, shopController.addShop);
router.post('/addCategories', shopController.addCategories);
router.post('/deleteCategories', shopController.deleteCategories);
module.exports = router;
