import HomePage from './HomePage/HomePage';
import OrderPage from './OrderPage/OrderPage';
import ProductPage from './ProductPage/ProductPage';
import ErrorPage from './ErrorPage/ErrorPage';
import TypePage from './TypePage/TypePage';
import CartPage from './CartPage/CartPage';
import RegisterPage from './RegisterPage/RegisterPage';
import SettingPage from './SettingPage/SettingPage';
import ShopPage from './ShopPage/ShopPage';
export { HomePage, OrderPage, ProductPage, ErrorPage, ShopPage, TypePage, CartPage, RegisterPage, SettingPage };
